=== Sentyee/XML-Proyect/XMLValidator.xsd
<?xml version="1.0"?>

<xs:schema version="1.0"
           xmlns:xs="http://www.w3.org/2001/XMLSchema"
           targetNamespace="https://www.victor.com"
           xmlns="https://www.victor.com"
           elementFormDefault="qualified">

    <xs:element name="AllData" type="AllData"/>

    <xs:complexType name="AllData">
        <xs:sequence>
            <xs:element name="Data" type="Data" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="Data">
        <xs:sequence>
            <xs:element name="Date" type="xs:integer"/>
            <xs:element name="Value" type="xs:string"/>
        </xs:sequence>
    </xs:complexType>

</xs:schema>

=== Sentyee/XML-Proyect/Adolescent fertility rate (Spain) (Result).xml
<?xml version="1.0" encoding="UTF-8"?>
<AllData xmlns="https://www.victor.com"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="https://www.victor.com XMLValidator.xsd">
    <Data>
        <Date>2019</Date>
        <Value/>
    </Data>
    <Data>
        <Date>2018</Date>
        <Value>7.4904</Value>
    </Data>
    <Data>
        <Date>2017</Date>
        <Value>7.725</Value>
    </Data>
    <Data>
        <Date>2016</Date>
        <Value>7.9744</Value>
    </Data>
    <Data>
        <Date>2015</Date>
        <Value>8.2238</Value>
    </Data>
    <Data>
        <Date>2014</Date>
        <Value>8.4732</Value>
    </Data>
    <Data>
        <Date>2013</Date>
        <Value>8.7226</Value>
    </Data>
    <Data>
        <Date>2012</Date>
        <Value>8.972</Value>
    </Data>
    <Data>
        <Date>2011</Date>
        <Value>9.7256</Value>
    </Data>
    <Data>
        <Date>2010</Date>
        <Value>10.4792</Value>
    </Data>
    <Data>
        <Date>2009</Date>
        <Value>11.2328</Value>
    </Data>
    <Data>
        <Date>2008</Date>
        <Value>11.9864</Value>
    </Data>
    <Data>
        <Date>2007</Date>
        <Value>12.74</Value>
    </Data>
    <Data>
        <Date>2006</Date>
        <Value>12.226</Value>
    </Data>
    <Data>
        <Date>2005</Date>
        <Value>11.712</Value>
    </Data>
    <Data>
        <Date>2004</Date>
        <Value>11.198</Value>
    </Data>
    <Data>
        <Date>2003</Date>
        <Value>10.684</Value>
    </Data>
    <Data>
        <Date>2002</Date>
        <Value>10.17</Value>
    </Data>
    <Data>
        <Date>2001</Date>
        <Value>9.7432</Value>
    </Data>
    <Data>
        <Date>2000</Date>
        <Value>9.3164</Value>
    </Data>
    <Data>
        <Date>1999</Date>
        <Value>8.8896</Value>
    </Data>
    <Data>
        <Date>1998</Date>
        <Value>8.4628</Value>
    </Data>
    <Data>
        <Date>1997</Date>
        <Value>8.036</Value>
    </Data>
    <Data>
        <Date>1996</Date>
        <Value>8.3646</Value>
    </Data>
    <Data>
        <Date>1995</Date>
        <Value>8.6932</Value>
    </Data>
    <Data>
        <Date>1994</Date>
        <Value>9.0218</Value>
    </Data>
    <Data>
        <Date>1993</Date>
        <Value>9.3504</Value>
    </Data>
    <Data>
        <Date>1992</Date>
        <Value>9.679</Value>
    </Data>
    <Data>
        <Date>1991</Date>
        <Value>10.7666</Value>
    </Data>
    <Data>
        <Date>1990</Date>
        <Value>11.8542</Value>
    </Data>
    <Data>
        <Date>1989</Date>
        <Value>12.9418</Value>
    </Data>
    <Data>
        <Date>1988</Date>
        <Value>14.0294</Value>
    </Data>
    <Data>
        <Date>1987</Date>
        <Value>15.117</Value>
    </Data>
    <Data>
        <Date>1986</Date>
        <Value>16.3432</Value>
    </Data>
    <Data>
        <Date>1985</Date>
        <Value>17.5694</Value>
    </Data>
    <Data>
        <Date>1984</Date>
        <Value>18.7956</Value>
    </Data>
    <Data>
        <Date>1983</Date>
        <Value>20.0218</Value>
    </Data>
    <Data>
        <Date>1982</Date>
        <Value>21.248</Value>
    </Data>
    <Data>
        <Date>1981</Date>
        <Value>22.124</Value>
    </Data>
    <Data>
        <Date>1980</Date>
        <Value>23</Value>
    </Data>
    <Data>
        <Date>1979</Date>
        <Value>23.876</Value>
    </Data>
    <Data>
        <Date>1978</Date>
        <Value>24.752</Value>
    </Data>
    <Data>
        <Date>1977</Date>
        <Value>25.628</Value>
    </Data>
    <Data>
        <Date>1976</Date>
        <Value>23.9258</Value>
    </Data>
    <Data>
        <Date>1975</Date>
        <Value>22.2236</Value>
    </Data>
    <Data>
        <Date>1974</Date>
        <Value>20.5214</Value>
    </Data>
    <Data>
        <Date>1973</Date>
        <Value>18.8192</Value>
    </Data>
    <Data>
        <Date>1972</Date>
        <Value>17.117</Value>
    </Data>
    <Data>
        <Date>1971</Date>
        <Value>16.2018</Value>
    </Data>
    <Data>
        <Date>1970</Date>
        <Value>15.2866</Value>
    </Data>
</AllData>
